# syntax=docker/dockerfile:1

# build
FROM golang:1.16-buster AS build

WORKDIR /app

COPY . .

RUN go build -o forum ./cmd

# deploy
FROM gcr.io/distroless/base-debian10

WORKDIR /

# COPY --from=build forum forum

COPY --from=build /app .

ENV PORT 3000

EXPOSE $PORT

ENTRYPOINT [ "./forum" ]

# multistage option but missing some image (C?)

# FROM golang:1.17 AS builder
# WORKDIR /app
# COPY . .
# RUN go build -o forum ./cmd/web

# FROM alpine:latest AS production
# COPY --from=builder /app .
# EXPOSE 5050
# CMD ["./forum"]